platform :ios, '11.0'
use_modular_headers!

target 'BlissHub' do
	pod 'SwiftLint'
	pod 'SwiftGen'

	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Alamofire', '5.0.0-rc.3'
	pod 'Moya/RxSwift', '14.0.0-beta.6'

	pod 'Kingfisher', '~> 5.0'
end
